### ISSUE TITLE
Support for "separate host"

### ISSUE THREAD

**Issue by bobvandevijver** [Tafkas/fritzbox-munin#15]
According to [this page](https://cweiske.de/tagebuch/munin-multiple-hosts.htm), it is possible to let Munin think some parts of the data belongs to some sort of subhost, which is logical to have for these scripts. However, there is no option to introduce this. 

Currently, I've added the option to the scripts myself, but I've not yet been able to migrate my current history to the new "subhost'. However, it should work nicely to split the graphs.

I might create a PR for this in the coming week, depending on my time.

**Comment by Tafkas** [comment]
You just set this up in your `munin.conf`. This is how mine looks like:

```
[home.tafkas.net;raspberrypi]
    address 127.0.0.1
    use_node_name yes

[home.tafkas.net;fritzbox]
    address 127.0.0.1
    use_node_name no
```

**Comment by bobvandevijver** [comment]
In order to make that word correctly, the config phase of the plugin should return a `host_name`. So I have basically the same now, but I do require a `host_name fritzbox` to be returned in the config.
