### ISSUE TITLE
Raspberry Pi Install Fritzconnection

### ISSUE THREAD

**Issue by Ang3er** [Tafkas/fritzbox-munin#2]
Error:  Failed building wheel for lxml
Command "/usr/bin/python -u -c "import setuptools, tokenize;**file**='/tmp/pip-build-VD68i6/lxml/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /tmp/pip-ux4_WQ-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-VD68i6/lxml/

How can this issue be solved... solutions to install the "wheel" pakage isn't solving the issue

**Comment by Tafkas** [comment]
Do you have the development libraries installed on your system? What system are you using? For a Debian system (like Ubuntu), this would be

`apt-get install libxml2-dev libxslt-dev`

**Comment by Ang3er** [comment]
Thank you very much, this tipp helped me very much. One further question: in wihich path do i find the scripts to copy them to munin. Thank you in advance. My system is running on debian jessie

**Comment by Tafkas** [comment]
I am glad I could help.

I put the scripts into **/usr/share/munin/plugins/fritzbox-munin** and then created symbolic links in **/etc/munin/plugins** (e.g. fritzbox_cpu_temperature -> /usr/share/munin/plugins/fritzbox-munin/fritzbox_cpu_temperature.py)

**Comment by Ang3er** [comment]
I tested some of the scripts and the results were different. Some classes import the class fritzbox_helper. The results when I run the script manual are Couldn't retrieve data ... I guess this is related to the imported class and the not establishing of the connection. The only parameters I have to define are my home IP Address of the fritzbox and the password is this correct?

**Comment by Tafkas** [comment]
Yes, do you run the scripts as munin? The scripts get the credentials from

```
server = os.environ['fritzbox_ip']
password = os.environ['fritzbox_password']
```

which are set in
**/etc/munin/plugin-conf.d/munin-node**

**Comment by Ang3er** [comment]
Yes I did unfortanatly: sudo -u munin python /etc/munin/plugins/fritzbox_cpu_temperature.py
Couldn't retrieve fritzbox cpu temperature (other scripts produce the same error, I guess this is the reason for not showing up in munin itself) The user of all (linked) scripts under plugins is root 

Btw thank you very much for helping me in this case :)

**Comment by andreas-marti** [comment]
I know it's an old discussion here...when I try to install fritzconnection with pip install fritzconnection, my raspberry crashes after start building wheel for lxml...? R3+, stretch...any ideas?

**Comment by PTomalak** [comment]
> I know it's an old discussion here...when I try to install fritzconnection with pip install fritzconnection, my raspberry crashes after start building wheel for lxml...? R3+, stretch...any ideas?

Same issue for me, Raspberry Pi zero

```
pi@raspberrypi:~ $ sudo pip install fritzconnection
[...]
Running setup.py bdist_wheel for fritzconnection ... done
Stored in directory: /root/.cache/pip/wheels/6f/66/26/0667ca19d5c8d4ccf1b12a1c593ff056a40a364eabcdd93c7f
Running setup.py bdist_wheel for lxml ... -
```

at this moment it gets unresponsive and don't finalize
