### ISSUE TITLE
Power consumption category

### ISSUE THREAD

**Issue by bobvandevijver** [Tafkas/fritzbox-munin#20]
Currently, the power consumption is in the same category as the network related stats, which seems weird to me. Maybe we can create the category `power`?

https://github.com/Tafkas/fritzbox-munin/blob/209eed91ae4701b755cd4b8c442e3827af3bc120/fritzbox_power_consumption.py#L47

**Comment by Tafkas** [comment]
Good catch. Or maybe just move to `system`?

**Comment by bobvandevijver** [comment]
`system` also works for me.

**Comment by Tafkas** [comment]
fixed by https://github.com/Tafkas/fritzbox-munin/commit/78a5a202cf78290220d2ab2af2b4442a3bb7b9ae

**Comment by bobvandevijver** [comment]
Great :)
