### ISSUE TITLE
3490 whit OS 7.01 not working the WAN Traffic. 

### ISSUE THREAD

**Issue by pictop** [Tafkas/fritzbox-munin#30]
On my munin installation the WAN traffic it doesn't show anything. All other graphs works fine. The FritzBox 3490 have a DSL Modem inside. But I use the first LAN Port as WAN Port. 

Here the output from the fritzbox_traffic.py
root@raspberrypi:/etc/munin/plugins# sudo -u munin python /etc/munin/plugins/fritzbox_traffic.py
Couldn't retrieve fritzbox traffic

Thank you for our Help!

**Comment by Tafkas** [comment]
Did you install the `fritzconnection` library?

**Comment by pictop** [comment]
Yes is installed.
All other fritzbox-munin works fine:
root@raspberrypi:~# sudo munin-run fritzbox_power_consumption.py
system.value 51
cpu.value 67
wifi.value 100
dsl.value 0
ab.value 0

root@raspberrypi:~# sudo munin-run fritzbox_memory_usage.py
free.value 40
cache.value 41
strict.value 19

I have only the problem with "fritzbox_traffic.py"
root@raspberrypi:~# sudo munin-run fritzbox_traffic.py
Couldn't retrieve fritzbox traffic

Thank you!

**Comment by Tafkas** [comment]
Did you enable the UPnP status information? (German interface: Heimnetz > Heimnetzübersicht > Netzwerkeinstellungen > Statusinformationen über UPnP übertragen)

**Comment by pictop** [comment]
That's it now works!! :)

Thank you very much!
