### ISSUE TITLE
Labor Firmware kills most munin stats: 07.08-65238 BETA

### ISSUE THREAD

**Issue by waywit** [Tafkas/fritzbox-munin#31]
Hi, thanks for this great munin plugin. 

I have updated my 7590 to Labor Firmware 07.08-65238 BETA and now most of the stats are gone :-(

```
2019/02/06 09:25:04 [WARNING] Service fritzbox_cpu_usage_py on xxx.fritz.box/127.0.0.1:4949 returned no data for label cpu
2019/02/06 09:25:11 [WARNING] Service fritzbox_wifi_devices_py on xxx.fritz.box/127.0.0.1:4949 returned no data for label wifi
2019/02/06 09:25:13 [WARNING] Service fritzbox_memory_usage_py on xxx.fritz.box/127.0.0.1:4949 returned no data for label cache
2019/02/06 09:25:13 [WARNING] Service fritzbox_memory_usage_py on xxx.fritz.box/127.0.0.1:4949 returned no data for label strict
2019/02/06 09:25:13 [WARNING] Service fritzbox_memory_usage_py on xxx.fritz.box/127.0.0.1:4949 returned no data for label free
2019/02/06 09:25:25 [WARNING] Service fritzbox_power_consumption_py on xxx.fritz.box/127.0.0.1:4949 returned no data for label system
2019/02/06 09:25:25 [WARNING] Service fritzbox_power_consumption_py on xxx.fritz.box/127.0.0.1:4949 returned no data for label ab
2019/02/06 09:25:25 [WARNING] Service fritzbox_power_consumption_py on xxx.fritz.box/127.0.0.1:4949 returned no data for label dsl
2019/02/06 09:25:25 [WARNING] Service fritzbox_power_consumption_py on xxx.fritz.box/127.0.0.1:4949 returned no data for label usb
2019/02/06 09:25:25 [WARNING] Service fritzbox_power_consumption_py on xxx.fritz.box/127.0.0.1:4949 returned no data for label wifi
2019/02/06 09:25:25 [WARNING] Service fritzbox_power_consumption_py on xxx.fritz.box/127.0.0.1:4949 returned no data for label cpu
2019/02/06 09:25:29 [WARNING] Service fritzbox_cpu_temperature_py on xxx.fritz.box/127.0.0.1:4949 returned no data for label temp
```

I am not sure, but I think that the "lua" pages are not accessible anymore?
- '/system/ecostat.lua'
- '/system/energy.lua'

I cannot load these pages after logging in with my fritz.box... I am actually using the scripts from tag 7.0.0, but also tried the ones from master.

**Comment by Yogi4301** [comment]
Hi,
I have the same problem - since the update to the firmware 7.08 (still beta) some plugins are working (especially those using fritzconnection) and some not. 

Working plugins:
fritzbox_connection_uptime  -> uses fritzconnection
fritzbox_uptime                    -> /system/energy.lua
fritzbox_traffic                       -> uses fritzconnection

Non working plugins:
fritzbox_power_consumption  -> /system/energy.lua
fritzbox_cpu_usage                 -> /system/ecostat.lua
fritzbox_memory_usage          -> /system/ecostat.lua
fritzbox_cpu_temperature       -> /system/ecostat.lua

Do you plan to update the plugins? The fritzbox_uptime plugin shows that the energy.lua pages still exists.

**Comment by Tafkas** [comment]
Hi there,

thank you for the heads up. I will look into it once the final version of the firmware is live. Until then I have no way to test this.

**Comment by Yogi4301** [comment]
Hi,
great - thanks! Please give me a note if I can support somehow.

Regards

**Comment by Yogi4301** [comment]
Great news - the final version 7.10 of Fritz!OS for 7590 is now available.

**Comment by Tafkas** [comment]
I upgraded the scripts to work with Fritz!OS 7.10. If you want to try it out, check out the latest master. Once everything is stable, I will push a new release. Some of the things are a little hacky for my taste. And non-german interfaces will probably break the scripts right now.

**Comment by waywit** [comment]
Hi and thanks :-) Yesterday I have updated to 7.10 and today the issue looks fixed...

I checked out the master and replaced the *.py files... I can now see the following stats again:
- Connected Wifi Devices
- Connection Uptime
- WAN traffic
- CPU Temp
- CPU usage
- Memory
- Power consumption
- Uptime

Great work, thanks!

**Comment by Yogi4301** [comment]
Hi,
great work - thanks. All plugin are working except one:

```
> 2019/04/09 18:15:09 [WARNING] Service fritzbox_power_consumption_py on fritzbox/127.0.0.1:4949 returned no data for label ab
> 2019/04/09 18:15:09 [WARNING] Service fritzbox_power_consumption_py on fritzbox/127.0.0.1:4949 returned no data for label usb
```

**Comment by Tafkas** [comment]
@Yogi4301 I think this has to do with Python 3 vs. Pyhton 2. The idea is to move all the scripts to Python 3 as Python 2 will be EOL later this year.

Edit: Check out the latest master. This should fix the issue.

**Comment by Yogi4301** [comment]
Now it works- thanks very much!
