### ISSUE TITLE
How to separate the graphy to a new node entry

### ISSUE THREAD

**Issue by CWempe** [Tafkas/fritzbox-munin#4]
I successfully installed this plugins.
But my fritzbox graphy are shown underneath my local server entry in the munin webinterface.
Is this by design?

I would like a separate entry for my fritzbox.

An examplere where this works are the munin plugins for mikrotik routers.
http://wiki.mikrotik.com/wiki/Munin_Monitoring

After the "_" the plugins expect a hostname in the filename.
You just create symlinks with the hostname to the plugins that end with "_".

**Comment by Tafkas** [comment]
I simply have defined the fritzbox as a host in **/etc/munin/munin.conf**

> [home.tafkas.net;fritzbox]
>     address 127.0.0.1
>     use_node_name no

This way the fritzbox gets its own entry:
![http://i.imgur.com/g8MZNkV.png](http://i.imgur.com/g8MZNkV.png)

**Comment by CWempe** [comment]
Does not work for me. :(

```
[Koeln;htpc]
    address 127.0.0.1
    use_node_name yes
    nvidia_gpu_temp.temp0.warning 85

[Koeln;fritbox]
    address 127.0.0.1
    use_node_name no
```

![image](https://cloud.githubusercontent.com/assets/1270359/14111468/24dad46a-f5cb-11e5-9589-0b9a555a35b8.png)

Any idea how to debug this to get to the root of this issue?
I have little experiance with munin. :)

How does munin now wich plugin belongs to which host of all use "127.0.0.1"?

btw: munin-node (munin-node) version 1.4.6.
fritzos6.5  branch

**Comment by CWempe** [comment]
I found the reason why it is working with the mikrotik plugin.

```
root@htpc:/etc/munin/plugins# ./mikrotikcpu_hm-mt01 config
host_name hm-mt01
graph_args -l 0 -r --vertical-label percent --lower-limit 0 --upper-limit 100
graph_title Mikrotik CPU usage

root@htpc:/etc/munin/plugins# ./fritzbox_cpu_usage config
graph_title AVM Fritz!Box CPU usage
```

The plugin returns a host_name parameter wich fritzbox does't. :/

**Comment by CWempe** [comment]
I included a static output for "host_name fritzbox".
https://github.com/CWempe/fritzbox-munin/tree/hostname_static

But I think this should be made dynamic in the future to support different hostnames/device names for multiple fritzboxes.

**Comment by CWempe** [comment]
I implemented this feature myself with dynamic hostname output.

Check out my branch https://github.com/CWempe/fritzbox-munin/tree/fritzos6.5 or wait for the Pull Request to be merged.

**Comment by 2Fake** [comment]
will this pull request merged into the master branch?
