### ISSUE TITLE
OS 7.25 requires username

### ISSUE THREAD

**Issue by msgrt** [Tafkas/fritzbox-munin#51]
After update to OS 7.25 connection to my 7590 stopped working.
During update a new standard fritzbox user account was created. Seems that this new user account is not required for web interface logins but for all the cmd logins from now on.

Error message with munin-run is
`ERROR - No SID received because of invalid password
Couldn't retrieve fritzbox uptime`

**Comment by Yogi4301** [comment]
I have the same problem - as shown in https://avm.de/service/schnittstellen/ the user management has changed. Is there a chance to adapt fritzbox-munin to work with version 7.25?

**Comment by Tafkas** [comment]
The current master, as well as the tag `7.25.0`, works with username and password.
