### ISSUE TITLE
support authentication with username

### ISSUE THREAD

**Issue by CWempe** [Tafkas/fritzbox-munin#9]
I had recently had to change from authentication "with password" to "username + password", because of other tools I use.

So now this plugin does not work anymore, because it does not support authentication with username.

Any change to implement this?

I think fritzconnection  does support this.

**Comment by Tafkas** [comment]
I just saw this morning that my Fritzbox is eligible for the 6.80 update. I will it update it on the weekend and look into this issue.

**Comment by CWempe** [comment]
I just implemented support for username. (see above)

But I don't know if my fix is alright.
Maybe we need error handling for users that still use authentication without username.

**Comment by CWempe** [comment]
Check out my branch https://github.com/CWempe/fritzbox-munin/tree/fritzos6.5 or wait for the Pull Request to be merged.
